# GitHub Workflow that automatically commits an empty
# commit to the master branch once a month.
#
# "Why?!" I hear you cry. Because otherwise GitHub silently
# stops running scheduled workflows on the repository and
# given this repositories purpose is to keep our Docker base
# images updated, that is a significant problem.
name: Keepalive auto-commit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Runs at midnight UTC on the 1st day of each month

jobs:
  keepalive-autocommit:
    name: Keepalive auto-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add empty commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          push: true
          message: Keepalive auto-commit
