# GitHub Workflow that automatically commits an empty
# commit to the master branch if the branch has not seen
# any activity in the past 50 days.
#
# "Why?!" I hear you cry. Because otherwise GitHub silently
# stops running scheduled workflows on the repository and
# given this repositories purpose is to keep our Docker base
# images updated, that is a significant problem.
name: Keepalive auto-commit
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  keepalive-autocommit:
    name: Keepalive auto-commit
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
